### ISSUE TITLE
Please tag release to a commit

### ISSUE THREAD

**Issue by StephenHodgson** [gilzoide/unity-key-value-store#2]
Hi there!

I'd love to use your package, but I'd prefer that you create a tag and make a release to get us started! 😃 

I also added your repo to the [OpenUPM registry](https://openupm.com), where it is easy for everyone to find and use your package. 

Thank you so much for your hard work, and be sure to check out my packages too 💜

**Comment by gilzoide** [comment]
Hi! Nice to see someone interested in this package =]
I've added the tag/release `1.0.0-preview1`, it should be installable through OpenUPM shortly.
I left it as a preview for now, even though I don't think things will change (or at least not much).

Thank you for the OpenUPM registration, I hope you enjoy using it \o/

**Comment by gilzoide** [comment]
I've also released the [SqliteKeyValueStore](https://github.com/gilzoide/unity-key-value-store-sqlite) implementation with tag 1.0.0-preview1 and pushed it to OpenUPM, if you're interested in a SQLite backed Key-Value Store for your games/apps =]

**Comment by StephenHodgson** [comment]
Any eta on iOS/macOS keystores?

**Comment by gilzoide** [comment]
> Any eta on iOS/macOS keystores?

No ETA on any additional KVS implementations, I listed them as possible implementations, but don't have short-term plans on implementing any of them.
Apple Keychain shouldn't be hard to implement, though, each Key-Value Store could map to a [Keychain Item](https://developer.apple.com/documentation/security/keychain_services/keychain_items) and data could be stored as Dictionaries internally.

What use case do you have for it?

By the way, this isn't pertaining to this issue, if you feel this conversation should continue, please open a new Discussion / Issue for it.

**Comment by gilzoide** [comment]
Hey @StephenHodgson, I was learning more about iOS keychain for a project here and remembered that a KVS implementation backed by Apple Keychain Items would be nice.
I did implement this in a separate package, for now tested only in the Unity Editor in macOS: https://github.com/gilzoide/unity-key-value-store-apple-keychain
Maybe it works for you =] Again, feel free to open Issues and Discussions in this new repo if you find anything.
